apiVersion: apps/v1
kind: Deployment
metadata:
    name: dz01-deployment
spec:
    replicas: 1
    selector:
       matchLabels:
          app: dz01-app
    template:
       metadata:
          labels:
             app: dz01-app
       spec:
          containers:
          - name: dz01
            image: kolemik/otus:dz01
            ports:
              - name: web 
                containerPort: 8000
            readinessProbe:
              httpGet:
                path: /otusapp/kolemik/health
                port: web
              failureThreshold: 1
              periodSeconds: 10
            startupProbe:
              httpGet:
                path: /otusapp/kolemik/hello
                port: web
              failureThreshold: 3
              periodSeconds: 30
