apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /otusapp/kolemik/$2
  name: rewrite
  namespace: default
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - backend:
              serviceName: dz01-service
              servicePort: 9000
            path: /otusapp/kolemik(/|$)(.*)