apiVersion: v1
kind: Service
metadata:
  name: dz01-service
spec:
  selector:
    app: dz01-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8000
      nodePort: 32000
  type: NodePort
