apiVersion: v1
kind: ConfigMap
metadata:
  name: dz02-config
data:
  GREETING: Bonjour
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dz02-chart.fullname" . }}-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
